#include "sofiload.h"
#include <iostream>
#include <codecvt>

Sofiload::Sofiload()
{
    insertHeader();
}

void Sofiload::append(std::unique_ptr<Combination> LC, const std::string& title)
{
  std::ofstream outfile;
  outfile.open("sofiplus.dat", std::ios_base::app); 
  if(!outfile.is_open())
    {
        std::cout << "Couldn't open the file in function append!\n";
        return; 
    }
  auto _LC = LC->getLoadCase();

  if(LC->getLimitState() == LimitState::ULS)
  {
    outfile << "LC " << _ULS << " TITL '" << title << "'" << " TYPE (D)\n";
    ++_ULS;    
  }  
  else 
  {
    outfile << "LC " << _SLS << " TITL '" << title << "'" << " TYPE (P)\n";
    ++_SLS; 
  }

  for(LoadCase& load : _LC)
  {
        outfile << "COPY " << load.loadNo << " FACT " << load.factor << "\n";
  }
  outfile << "\n"; 
  outfile.close();
}

void Sofiload::insertHeader()
{
std::ofstream outfile;
outfile.open("sofiplus.dat", std::ios_base::app );
outfile << "$ Generated by SofiMake v0.1, Author: Maciej Zieliński, 04.06.2023.\n";
outfile << "+PROG SOFILOAD urs:17.1\n$ HEAD $(POZYCJA)\necho load no\necho act no\n\n";
outfile.close();
}